# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\pair_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PairWindow(object):
    def setupUi(self, PairWindow):
        PairWindow.setObjectName("PairWindow")
        PairWindow.resize(640, 609)
        PairWindow.setStyleSheet("#PairWindow {\n"
"    background-color: #F9F7F7;\n"
"}\n"
"\n"
"QLabel#source_channel {\n"
"    border: 1px solid #3F72AF;\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel#target_channel {\n"
"    border: 1px solid #3F72AF;\n"
"    border-radius: 5px;\n"
"}")
        self.confirm = QtWidgets.QPushButton(PairWindow)
        self.confirm.setGeometry(QtCore.QRect(260, 530, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("\n"
"QPushButton#confirm {\n"
"    background-color: #3F72AF;\n"
"    color: #F9F7F7;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#confirm:hover {\n"
"    background-color: #F9F7F7;\n"
"    color: #3F72AF;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #3F72AF;\n"
"}\n"
"")
        self.confirm.setObjectName("confirm")
        self.target_group = QtWidgets.QGroupBox(PairWindow)
        self.target_group.setGeometry(QtCore.QRect(400, 10, 171, 91))
        self.target_group.setTitle("")
        self.target_group.setObjectName("target_group")
        self.target_channel = QtWidgets.QLabel(self.target_group)
        self.target_channel.setGeometry(QtCore.QRect(70, 40, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.target_channel.setFont(font)
        self.target_channel.setStyleSheet("")
        self.target_channel.setAlignment(QtCore.Qt.AlignCenter)
        self.target_channel.setObjectName("target_channel")
        self.target_title = QtWidgets.QLabel(self.target_group)
        self.target_title.setGeometry(QtCore.QRect(0, 0, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.target_title.setFont(font)
        self.target_title.setAlignment(QtCore.Qt.AlignCenter)
        self.target_title.setObjectName("target_title")
        self.source_group = QtWidgets.QGroupBox(PairWindow)
        self.source_group.setGeometry(QtCore.QRect(69, 10, 171, 90))
        self.source_group.setStyleSheet("")
        self.source_group.setTitle("")
        self.source_group.setObjectName("source_group")
        self.source_channel = QtWidgets.QLabel(self.source_group)
        self.source_channel.setGeometry(QtCore.QRect(70, 40, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.source_channel.setFont(font)
        self.source_channel.setStyleSheet("")
        self.source_channel.setAlignment(QtCore.Qt.AlignCenter)
        self.source_channel.setObjectName("source_channel")
        self.source_title = QtWidgets.QLabel(self.source_group)
        self.source_title.setGeometry(QtCore.QRect(0, 0, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.source_title.setFont(font)
        self.source_title.setAlignment(QtCore.Qt.AlignCenter)
        self.source_title.setObjectName("source_title")
        self.cmd_group = QtWidgets.QGroupBox(PairWindow)
        self.cmd_group.setGeometry(QtCore.QRect(20, 110, 600, 150))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cmd_group.setFont(font)
        self.cmd_group.setStyleSheet("QGroupBox::title {\n"
"margin-top: 10px;\n"
"subcontrol-position: top center;\n"
"}\n"
"#cmd_group{\n"
"border:0;\n"
"}\n"
"QWidget#container {\n"
"    background-color: #DBE2EF;\n"
"}\n"
"QScrollArea {\n"
"    border: 1px solid #DBE2EF;\n"
"    background-color: #DBE2EF;\n"
"}")
        self.cmd_group.setObjectName("cmd_group")
        self.input_group = QtWidgets.QGroupBox(PairWindow)
        self.input_group.setGeometry(QtCore.QRect(69, 270, 501, 241))
        self.input_group.setStyleSheet("#input_group {\n"
"    border: 1px solid #3F72AF;\n"
"    border-radius: 10px;\n"
"}")
        self.input_group.setTitle("")
        self.input_group.setObjectName("input_group")
        self.add = QtWidgets.QPushButton(self.input_group)
        self.add.setGeometry(QtCore.QRect(110, 190, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add.setFont(font)
        self.add.setStyleSheet("\n"
"QPushButton#add {\n"
"    background-color: #3F72AF;\n"
"    color: #F9F7F7;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#add:hover {\n"
"    background-color: #F9F7F7;\n"
"    color: #3F72AF;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #3F72AF;\n"
"}\n"
"")
        self.add.setObjectName("add")
        self.label = QtWidgets.QLabel(self.input_group)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.source_cmd_box = QtWidgets.QComboBox(self.input_group)
        self.source_cmd_box.setGeometry(QtCore.QRect(20, 60, 211, 30))
        self.source_cmd_box.setObjectName("source_cmd_box")
        self.label_4 = QtWidgets.QLabel(self.input_group)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.target_cmd_box = QtWidgets.QComboBox(self.input_group)
        self.target_cmd_box.setGeometry(QtCore.QRect(20, 140, 211, 30))
        self.target_cmd_box.setObjectName("target_cmd_box")
        self.level_check = QtWidgets.QCheckBox(self.input_group)
        self.level_check.setGeometry(QtCore.QRect(260, 20, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.level_check.setFont(font)
        self.level_check.setObjectName("level_check")
        self.duration_check = QtWidgets.QCheckBox(self.input_group)
        self.duration_check.setGeometry(QtCore.QRect(260, 60, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.duration_check.setFont(font)
        self.duration_check.setObjectName("duration_check")
        self.timeout_check = QtWidgets.QCheckBox(self.input_group)
        self.timeout_check.setGeometry(QtCore.QRect(260, 100, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.timeout_check.setFont(font)
        self.timeout_check.setObjectName("timeout_check")
        self.delay_check = QtWidgets.QCheckBox(self.input_group)
        self.delay_check.setGeometry(QtCore.QRect(260, 140, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.delay_check.setFont(font)
        self.delay_check.setObjectName("delay_check")
        self.level_edit = QtWidgets.QLineEdit(self.input_group)
        self.level_edit.setGeometry(QtCore.QRect(370, 20, 110, 25))
        self.level_edit.setObjectName("level_edit")
        self.duration_edit = QtWidgets.QLineEdit(self.input_group)
        self.duration_edit.setGeometry(QtCore.QRect(370, 60, 110, 25))
        self.duration_edit.setObjectName("duration_edit")
        self.timeout_edit = QtWidgets.QLineEdit(self.input_group)
        self.timeout_edit.setGeometry(QtCore.QRect(370, 100, 110, 25))
        self.timeout_edit.setObjectName("timeout_edit")
        self.delay_edit = QtWidgets.QLineEdit(self.input_group)
        self.delay_edit.setGeometry(QtCore.QRect(370, 140, 110, 25))
        self.delay_edit.setObjectName("delay_edit")

        self.retranslateUi(PairWindow)
        QtCore.QMetaObject.connectSlotsByName(PairWindow)

    def retranslateUi(self, PairWindow):
        _translate = QtCore.QCoreApplication.translate
        PairWindow.setWindowTitle(_translate("PairWindow", "Form"))
        self.confirm.setText(_translate("PairWindow", "完成"))
        self.target_channel.setText(_translate("PairWindow", "5"))
        self.target_title.setText(_translate("PairWindow", "Target Endpoint"))
        self.source_channel.setText(_translate("PairWindow", "2"))
        self.source_title.setText(_translate("PairWindow", "Source Endpoint"))
        self.cmd_group.setTitle(_translate("PairWindow", "已加入的配對"))
        self.add.setText(_translate("PairWindow", "新增至列表"))
        self.label.setText(_translate("PairWindow", "Source Command"))
        self.label_4.setText(_translate("PairWindow", "Target Command"))
        self.level_check.setText(_translate("PairWindow", "Level"))
        self.duration_check.setText(_translate("PairWindow", "Duration"))
        self.timeout_check.setText(_translate("PairWindow", "Timeout(ms)"))
        self.delay_check.setText(_translate("PairWindow", "Delay(ms)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PairWindow = QtWidgets.QWidget()
    ui = Ui_PairWindow()
    ui.setupUi(PairWindow)
    PairWindow.show()
    sys.exit(app.exec_())
